# Generated by Django 4.2.4 on 2024-01-03 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0011_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='tempo_duracao',
        ),
    ]
