# Generated by Django 4.2.4 on 2024-01-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0012_remove_emprestimo_tempo_duracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='usuario',
        ),
    ]
